import { Player } from './types';

export const INITIAL_PLAYERS: Player[] = [
  { id: '1', name: 'Guilherme', rating: 4.33, gender: 'H' },
  { id: '2', name: 'Iago', rating: 4.0, gender: 'H' },
  { id: '3', name: 'Witalo', rating: 4.0, gender: 'H' },
  { id: '4', name: 'Gusttavo', rating: 3.83, gender: 'H' },
  { id: '5', name: 'Mikael', rating: 3.67, gender: 'H' },
  { id: '6', name: 'Jéssica', rating: 3.5, gender: 'M' },
  { id: '7', name: 'Jhonny', rating: 3.5, gender: 'H' },
  { id: '8', name: 'João Victor', rating: 3.33, gender: 'H' },
  { id: '9', name: 'Vitória', rating: 3.17, gender: 'M' },
  { id: '10', name: 'Lucas', rating: 3.17, gender: 'H' },
  { id: '11', name: 'Eric', rating: 3.17, gender: 'H' },
  { id: '12', name: 'Castelinho', rating: 2.83, gender: 'H' },
  { id: '13', name: 'Dudu Lívio', rating: 2.83, gender: 'H' },
  { id: '14', name: 'Val', rating: 3.17, gender: 'M' },
  { id: '15', name: 'Paulo', rating: 2.67, gender: 'H' },
  { id: '16', name: 'William', rating: 2.67, gender: 'H' },
  { id: '17', name: 'Arthur', rating: 3.17, gender: 'H' },
  { id: '18', name: 'Cláudia', rating: 2.17, gender: 'M' },
  { id: '19', name: 'Sthefany', rating: 2.17, gender: 'M' },
  { id: '20', name: 'Tandim', rating: 2.0, gender: 'H' },
  { id: '21', name: 'Animércia', rating: 2.0, gender: 'M' },
  { id: '22', name: 'Tico', rating: 2.0, gender: 'H' },
  { id: '23', name: 'Giu', rating: 3.17, gender: 'M' },
  { id: '24', name: 'Luísa', rating: 1.67, gender: 'M' },
  { id: '25', name: 'Hanna', rating: 1.17, gender: 'M' },
  { id: '26', name: 'Juliete', rating: 1.0, gender: 'M' },
];
